### ISSUE TITLE
make isssue in one one 

### ISSUE THREAD

**Issue by SankN22** [mayank-02/multithreading-library#1]
make is not working in one one. It shows following when make command is run
```
gcc -I include -g -Wall -fpic -DDEBUG -c src/mthread.c -o obj/mthread.o
src/mthread.c:67:21: error: static declaration of ‘gettid’ follows non-static declaration
   67 | static inline pid_t gettid(void) {
      |                     ^~~~~~
In file included from /usr/include/unistd.h:1218,
                 from src/mthread.c:14:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ with type ‘__pid_t(void)’ {aka ‘int(void)’}
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
make: *** [Makefile:53: obj/mthread.o] Error 1
```

**Comment by mayank-02** [comment]
Hey @SankN22, can you try dropping `static inline` from the function definition for now and build again?
https://github.com/mayank-02/multithreading-library/blob/bb09262b4c06b97597a99cc11934aca650b16747/one-one/src/mthread.c#L67

Let me know if that doesn't help.

**Comment by SankN22** [comment]
yes issue resolved .Thank you !

**Comment by mayank-02** [comment]
Fixed in https://github.com/mayank-02/multithreading-library/commit/3df2df3068c80851103e1d910e0d21b5ac8918ff. Thanks for reporting!
